### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by JamyGolden** [stigger/trakt-for-appletv#24] opened 2022-08-22 13:16 UTC
1. I ran `python3 ./tvscrobbler.py` and things seem to work correctly.
2. I got asked to authorize my trakt.tv account and a url is provided. I clicked that and got a pin which I provide to the CLI
3. After that I got asked to enter the code displayed on my Apple TV. I entered that code into the CLI and then got the following error

```
...
Enter code displayed by Apple TV: 1798
ready!
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7faf87fc57b0>
Traceback (most recent call last):
  File "/home/jamygolden/projects/trakt-for-appletv/./tvscrobbler.py", line 32, in <module>
    asyncio.run(launch(ScrobblingRemoteProtocol(load_config())))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/jamygolden/projects/trakt-for-appletv/./tvscrobbler.py", line 25, in launch
    await tv_protocol.connect(atv)
  File "/home/jamygolden/projects/trakt-for-appletv/scrobbling.py", line 64, in connect
    protocol.add_listener(self.message_received, ProtocolMessage.SET_STATE_MESSAGE)
AttributeError: 'MrpProtocol' object has no attribute 'add_listener'
```

Any ideas what the problem is?

**Comment by stigger** [comment] 2022-08-22 14:13
As a workaround, please try downgrading pyatv to 0.9.1. I've updated requirements.txt.

Duplicate of #21

**Closed as completed by stigger** 2022-08-22 14:13 UTC
